# Description: Configuration for GPT4O
name: "claude"
planner: 
    model_name: "claude-3-5-sonnet-20240620"
    is_local: false
navigator:
    model_name: "claude-3-haiku-20240307"
    is_local: false
generator:
    model_name: "claude-3-5-sonnet-20240620"
    is_local: false
executor:
    model_name: "gemini-1.5-pro-latest"
    is_local: false