# Description: Configuration for GPT4O
name: "gemini"
planner: 
    model_name: gemini-1.5-pro-latest
    is_local: false
navigator:
    model_name: claude-3-haiku-20240307
    is_local: false
generator:
    model_name: MaziyarPanahi/WizardLM-2-8x22B-AWQ
    is_local: true
executor:
    model_name: "gemini-1.5-pro-latest"
    is_local: false